# automatically generated by the FlatBuffers compiler, do not modify

# namespace: events

class EventType(object):
    NONE = 0
    NewImageEvent = 1
    ImageScoredEvent = 2
    ImageStoredEvent = 3
    ImageDeletedEvent = 4
