[package]
name = "plyoreacto"
version = "0.1.0"
edition = "2021"
authors = ["Joe Stubbs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "plyoreacto"
path = "src/main.rs"


[dependencies]
zmq = "0.9"